package com.example.varthakassesment.Model;

import jakarta.persistence.*;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "InternalUSER")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "user_id")
    private UUID userId;


    // User belongs to one Customer
    @ManyToOne
    @JoinColumn(name = "Customer_Id", nullable = false)
    private Customer customer;


    // User has one Role
    @ManyToOne
    @JoinColumn(name = "role_Id", nullable = false)
    private Role role;


    // User belongs to one Company
    @ManyToOne
    @JoinColumn(name = "Company_Id", nullable = false)
    private Company company;


    // User has one Status
    @ManyToOne
    @JoinColumn(name = "status_Id", nullable = false)
    private Status status;


    // ID originally generated by the external customer API
    @Column(name = "EXTERNAL_USER_ID", nullable = false)
    private String externalUserId;


    @Column(name = "name", nullable = false)
    private String name;


    @Column(name = "email", nullable = false)
    private String email;


    @Column(name = "phone")
    private String phone;


    // Timestamps received from the external API
    @Column(name = "created_At")
    private Instant externalCreatedAt;


    @Column(name = "updated_At")
    private Instant externalUpdatedAt;


    // 1 = active/present true
    // 0 =  deactivated false
    @Column(name = "active", nullable = false)
    private int active = 1;

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }


    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }


    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }


    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }


    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }


    public String getExternalUserId() {
        return externalUserId;
    }

    public void setExternalUserId(String externalUserId) {
        this.externalUserId = externalUserId;
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }


    public Instant getExternalCreatedAt() {
        return externalCreatedAt;
    }

    public void setExternalCreatedAt(Instant externalCreatedAt) {
        this.externalCreatedAt = externalCreatedAt;
    }


    public Instant getExternalUpdatedAt() {
        return externalUpdatedAt;
    }

    public void setExternalUpdatedAt(Instant externalUpdatedAt) {
        this.externalUpdatedAt = externalUpdatedAt;
    }


    public int getActive() {
        return active;
    }

    public void setActive(int active) {
        this.active = active;
    }
}